CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	CNT INT DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE,
	FILENAME VARCHAR(4000)
);
DROP TABLE BOARD;
DROP TABLE MEMBER;
SELECT * FROM BOARD;
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(1,'제목','관리자','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(2,'제목','관리자','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(3,'제목','관리자','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(4,'제목','관리자','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(5,'제목','관리자','내용');